# -*- coding: utf-8 -*-
"""YmgkBafra.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QAOoTrxnptDsxZ_05EVSZfCfhAbZtxa-
"""

from google.colab import drive
drive.mount("/content/drive")

import numpy as np
from matplotlib import pyplot as plt
import pandas as pd
import seaborn as sea
data = pd.read_excel("/content/drive/My Drive/YMGK/denemebafra.xlsx")
data['PM10'] = data['PM10'].astype('float')
data['PM10Debi'] = data['PM10Debi'].astype('float')
data['SO2'] = data['SO2'].astype('float')
data['NO2'] = data['NO2'].astype('float')
data['NOX'] = data['NOX'].astype('float')
data['NO'] = data['NO'].astype('float')
data['C'] = data['C'].astype('float')
data['katıatık'] = data['katıatık'].astype('float')



print(data.mean())

data = data.fillna(data.mean())


plt.figure(figsize=(12,6))
plt.plot(data.Tarih,data.katıatık)
plt.show()


plt.figure(figsize=(24,12))
plt.subplot(2,2,1)
plt.plot(data.Tarih,data.PM10,color="red")
plt.plot(data.Tarih,data.SO2,color="blue")
plt.plot(data.Tarih,data.NO2,color="black")
plt.plot(data.Tarih,data.NOX,color="orange")
plt.plot(data.Tarih,data.NO,color="green")
plt.plot(data.Tarih,data.C,color="purple")
plt.plot(data.Tarih,data.katıatık,color="yellow")


plt.xlabel("Tarih")
plt.ylabel("PM10-SO2-CO-NO2-NOX-NO-C Miktarı")
plt.title("KATI ATIK  DEĞİŞİMİ ")

plt.subplot(2,2,2)
plt.plot(data.Tarih,data.katıatık,color="yellow")
plt.xlabel("Tarih")
plt.ylabel("KATI YOĞUNLUĞU")
plt.title("Zamana Göre Atık  değişimi")

plt.show()


sea.scatterplot(x ="PM10",y="NO2", data=data)
plt.show()
sea.scatterplot(x ="PM10",y="katıatık", data=data)
plt.show()